[package]
name = "svg-strip"
version = "1.1.0"
edition = "2024"
rust-version = "1.85"
description = "Fast and aggressive SVG minification CLI tool for shrinking SVGs for inline HTML, Vue and Svelte component templates and standalone files"
license = "MIT"
repository = "https://github.com/madLinux7/svg-strip"
readme = "README.md"
keywords = ["svg", "minify", "cli", "optimizer"]
categories = ["command-line-utilities", "web-programming"]

[dependencies]
colored = "3.1.1"
lazy_static = "1.5.0"
regex = "1.12.3"
xml-rs = "1.0.0"
xmltree = "0.11"
